services:
  adolla:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}:/home/adolla/.adolla
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
